euslisp/catkin.cmake

Result variable of execute_process will be defined always, we need to
check the value of the variable

[euslisp] fix syntax of cmake of euslisp.

---

roseus/euslisp/roseus-utils.l

enable alpha (keyword argument) when converting eusmodel to ros marker

enable alpha when converting eusmodel to ros marker

---

roseus/catkin.cmake
roseus/cmake/roseus.cmake

@garaemon, this is workaround for using new geneus messages generator, which packae should I test, jsk_control? jsk_pcl_ros?
I also afraid that we should not run this script on ros buildfirm once new geneus is accepted.
- add example to use new generate_all_roseus_messages()
- add new macro, generate_all_roseus_message() to generate all dependency  msgs using new geneus written by python

use new genmsg

---

roseus/roseus.cpp

from this discussion https://github.com/jsk-ros-pkg/jsk_roseus/issues/184
```
[ERROR] [1422277405.614847053]: you may not return valid value in service callback
[FATAL] [1422277405.615029525]: ASSERTION FAILED
file = /home/leus/ros/hydro/src/jsk-ros-pkg/jsk_roseus/roseus/roseus.cpp
line = 241
cond = a!=NIL
```

[roseus] If user return invalid instance in service callback, print error message

---

roseus/euslisp/roseus-utils.l

Finally, message_filters for roseus is implemented now
sample code
```
;; sample                                                                                                                   
(defclass image-caminfo-synchronizer
:super exact-time-message-filter)
(defmethod image-caminfo-synchronizer
(:callback (image caminfo)
(print (list image caminfo))
(print (send-all (list image caminfo) :header :stamp))
))
(ros::roseus "hoge")
(ros::roseus-add-msgs "sensor_msgs")
;; test                                                                                                                     
(setq hoge (instance image-caminfo-synchronizer :init
(list (list "/multisense/left/image_rect_color" sensor_msgs::Image)
(list "/multisense/left/camera_info" sensor_msgs::CameraInfo)))) …
```

[roseus] Add class to synchronize multiple topics with the same timestamp like message_filters

---

roseus/CMakeLists.txt

From #234.
#234 problem occures when below condition is true.
- roseus is installed through apt-get
- roseus src is not in your overlay workspace
- There is the package which depends on roseus
This PR will change to install the binary to lib/roseus to share/roseus/bin.

[roseus] Install roseus binary to share directory

---

roseus/CMakeLists.txt
roseus/euslisp/roseus-utils.l
roseus/euslisp/roseus.l

[roseus.l] remove global variable in ros::find-load-msg-path
[roseus-utils.l] do not use too simple variable name :call-callback-if-possible of exact-time-message-filter

rebase for youhei's patch

---

roseus/test/test-genmsg.sh

old ( not released as if Apr 14) does not have jobserver options and fail to configure
Thanks to catch this @wkentaro

do not raise error for old catkin

---

roseus/CMakeLists.txt

- [roseus/CMkeLists.txt] in some cases, rosversion tf2_ros did not resspond the results, use tf2_ros_VERSION, since this is only for old tf2, so we can remove this

fix those who did not have rosversion

---

roseus_smach/CMakeLists.txt
roseus_smach/package.xml
roseus_smach/test/test-parallel-state-machine.l
roseus_smach/test/test-samples.l
roseus_smach/test/test_parallel_state_machine_sample.launch

add tests for
- existing samples for basic SMACH features ( simple, nested and userdata)
- parallel executive state machine
- async join-able state machine
and add them to `CMakeLists.txt` as `rostest`
This is another PR of https://github.com/jsk-ros-pkg/jsk_roseus/pull/293.

[roseus_smach] add tests for roseus smach

---

roseus/CMakeLists.txt
roseus/eustf.cpp

fix for compiling roseus on OSX/Clang environment

Fix for clang

---

roseus/cmake/roseus.cmake

It may solve https://github.com/jsk-ros-pkg/jsk_roseus/issues/312

[roseus] Unset DISPLAY environmental variable when generating eusdoc to avoid init-xwindow error

---

jsk_roseus/package.xml

this will eliminate
```
WARNING: Metapackage "jsk_roseus" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
```

adding build_depends to package.xml is wrong.

---

roseus_mongo/euslisp/json/json-decode.l
roseus_mongo/test/test-json-decode.l

With this change, we can use `assoc` with keyword instead of string (now we don't need `:test #'string=`)

[roseus_mongo/euslisp/json/json-decode.l] use keyword for key as default

---

roseus/euslisp/roseus.l
roseus/test/test-roseus.l

ros::resolve-ros-path returns when taking non existing package name

Fix resolve

---

roseus/CMakeLists.txt
roseus/euslisp/roseus.l
roseus/roseus.cpp
roseus/test/test-timer.l
roseus/test/test-timer.test

based on http://wiki.ros.org/roscpp/Overview/Timers, see #237
currently, proposed API is something like this.
```
(defun cb1 (event)
(let (msg)
(setq msg (instance std_msgs::string :init))
(send msg :data (format nil "hello world ~a" (send (ros::time-now) :sec-nsec)))
(ros::publish "chatter1" msg)
))
(ros::create-timer 0.1 #'cb1)
```
another possibility is
```
(ros::create-timer ros::Timer(0.1) #'cb1)
```
I also did not implement ros::TimerEvent class(http://wiki.ros.org/roscpp/Overview/Timers#Callback_Signature), does it should be class instance? or just to pass 
`(list last_expected last_real current_expected current_real profile.last_duration)` is ok for you?

roseus.cpp: add ros::create-timer function

---

.travis.yml

It's a hotfix.
I will create another branch to pass these test on jade.

[roseus] Ignore duration test on jade for a while

---

roseus/euslisp/actionlib.l
roseus/roseus.cpp

Fix error of #370 and #369 by ignoring jade testing(#372).

[roseus] Resolve jade error on prs of #370 and #369

---

roseus/roseus.cpp

```lisp
(ros::rospack-plugins "nodelet" "plugin")
=>
(("laser_proc" . "/opt/ros/hydro/share/laser_proc/nodelets.xml") ("velodyne_driver" . "/opt/ros/hydro/share/velodyne_driver/nodelet_velodyne.xml") ("yocs_velocity_smoother" . "/opt/ros/hydro/share/yocs_velocity_smoother/plugins/nodelets.xml") ("jsk_perception" . "/home/lueda/ros/hydro/src/jsk-ros-pkg/jsk_recognition/jsk_perception/jsk_perception_nodelets.xml") ("image_rotate" . "/home/lueda/ros/hydro/src/image_pipeline/image_rotate/nodelet_plugins.xml") ("stereo_image_proc" . "/home/lueda/ros/hydro/src/image_pipeline/stereo_image_proc/nodelet_plugins.xml") ("depth_image_proc" . "/home/lueda/ros/hydro/src/image_pipeline/depth_image_proc/nodelet_plugins.xml") ("kobuki_bumper2pc" . …
```

[roseus] Add ros::rospack-plugins function. It is equivalent to `rospack plugins`

---

roseus/roseus.cpp

I think the error of get-num-publishers is trivial. If calling `get-num-publishers` fails, this returns nil, which is enough to know it fails.

[roseus/roseus.cpp] remove trivial error message from get-num-publishers

---

roseus_smach/src/state-machine.l

`:add-node`や `:goal-state`を使ってstate を定義する前に `:add-transition` で遷移を定義すると、state名自体をnode としてしまい、混乱を招く気がしたので、warning messageが出るように変更
例
```
(setq sm (instance state-machine :init))
(send sm :add-node (instance state :init :hoge 'hoge-func))
(send sm :add-transition :hoge :success t)
(send sm :start-state :hoge)
(send sm :goal-state (list :success))
```
などとして実行すると、遷移した結果 `:success` に遷移するが、これは
`(send sm :goal-state (list :success))`
によって定義された:successと異なるので、
まだ終端に来たと判断せずにエラーが出る。

[roseus_smach] warning message for :goal-state

---

roseus_mongo/CMakeLists.txt
roseus_mongo/test/temp_mongodb_store.xml
roseus_mongo/test/test_mongo_client_hydro.test

- [roseus_mongo/test/temp_mongodb_store.xml] update launch file path with fix https://github.com/strands-project/mongodb_store/pull/151
- [roseus_mongo/test/test_mongo_client_hydro.test] moved deprecated test launch file for hydro
- [roseus_mongo/CMakeLists.txt] updated to test only CATKIN_ENABLE_TESTING; check mongodb_store version and switch test launch file

[roseus_mongo] update test launch file along with with fix https://github.com/strands-project/mongodb_store/pull/151

---

.travis.rosinstall

new version was released on 0.1.18 https://github.com/strands-project/mongodb_store/commit/0d4b0e7813fa5305f964b3ccd8e662e0d6365c67

[.travis.rosinstall] remove mongodb_store from .travis.rosinstall

---

roseus/test/test-genmsg.catkin.test
roseus/test/test-genmsg.sh

see #335 (60a4127)
- test/test-genmsg.catkin.test: disable --remove-message test, which does not work on paralllel execution
- test/test-genmsg: add debug message

disable remove-message test

---

.travis.yml
roseus/euslisp/roseus-utils.l
roseus/test/test-roseus.l
roseus/test/test-roseus.test

not yet included test code and docs (I'll make after rinko)
but like below
@mizmizo you can use this
```lisp
;; test-img.l
;; Author: Yuki Furuta <furushchev@jsk.imi.i.u-tokyo.ac.jp>
(require :pr2 "package://pr2eus/pr2.l")
(ros::roseus "hoge")
(pr2)
(send *pr2* :look-at-target (send *pr2* :rarm :end-coords))
(setq cam (send *pr2* :wide_stereo-left))
(send cam :create-viewer)
(send cam :draw-objects (list *pr2*))
(setq img (send cam :get-image))
(ros::advertise "image" sensor_msgs::Image 5)
(unix:sleep 2)
(setq seq 0)
(ros::rate 10)
(do-until-key
(setq msg (ros::image->sensor_msgs/Image img :seq (inc seq) :frame_id "hoge"))
(ros::publish "image" msg)
(ros::sleep))
```

[roseus/euslisp/roseus-utils.l] add image conversion to ros msg

---

roseus/CMakeLists.txt
roseus/cmake/roseus.cmake
roseus/roseus.cpp

another implementation would be define get_string in eus.h as #define and write `#define get_string eus_get_string` in roseus.cpp, but I choose this PR since
- adding get_string to eus.h seems exceptional in other function/macro defined in eus.h
- ??

re-define get_string for osx

---

.travis.yml
roseus/CMakeLists.txt
roseus/package.xml

reported at http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_roseus-indigo-deb-false-true/927/console
```
[roseus:cmake] -- roseus: 4 messages, 2 services
09:57:06 
[roseus:cmake] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:163 (message):
09:57:06 
[roseus:cmake]   catkin_package() DEPENDS on 'coreutils' which must be find_package()-ed
09:57:06 
[roseus:cmake]   before.  If it is a catkin package it can be declared as CATKIN_DEPENDS
09:57:06 
[roseus:cmake]   instead without find_package()-ing it.
09:57:06 
[roseus:cmake] Call Stack (most recent call first):
09:57:06 
[roseus:cmake]   /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
09:57:06 
[roseus:cmake]   CMakeLists.txt:139 (catkin_package)
```

[roseus] fix config of dependency: coreutils

---

roseus/roseus.cpp
roseus/test/param-test.l

```bash
(ros::roseus "test_param")
(ros::set-param "foo" "bar")
(ros::get-param "foo") ;; => "bar"
(ros::del-param "foo") ;; => t
(ros::get-param "foo") ;; => nil
(ros::del-param "does_not_exists") ;; => nil
```

[roseus] add ros::del-param

---

roseus/roseus.cpp
roseus/test/param-test.l

- `ros::get-param-cashed` -> `ros::get-param-cached`
- fix test for cache
This pull request should be merged after https://github.com/jsk-ros-pkg/jsk_roseus/pull/466

[roseus] fix typo / test: ros::get-param-cached

---

roseus_smach/src/state-machine-utils.l

```lisp
1.irteusgl$ exec-smach-with-spin (smach-simple) nil :iterate t
Execute :foo ? (Y or N): y
Execute state FOO
[ INFO] [1468997737.345744434]: trans: (#<transition #X63a88d0 :outcome2 #<state #X6398d20 :foo>->#<state #X63a89d8 :outcome4>> #<transition #X63a8690 :outcome1 #<state #X6398d20 :foo>->#<state #X63a8990 :bar>>)
Execute :bar ? (Y or N): y
Execute state BAR
[ INFO] [1468997738.921604165]: trans: (#<transition #X63a6380 :outcome2 #<state #X63a8990 :bar>->#<state #X6398d20 :foo>>)
Execute :foo ? (Y or N): n
[ WARN] [1468997740.513418288]: aborting...
nil
```

[roseus_smach/src/state-machine-utils.l] support y-or-n-p when iterate mode

---

roseus/CMakeLists.txt

overtake https://github.com/jsk-ros-pkg/jsk_roseus/pull/425 because source code is no more up-to-date.
- add section `CATKIN_ENABLE_TESTING` for testing
> btw, what is the advantage of using CATKIN_ENABLE_TESTING ?
- it is a recommended way to do so (http://docs.ros.org/jade/api/catkin/html/howto/format1/rostest_configuration.html)
- catkin doesn't compile executable only for test in `build` time.
- clear to read cmake file

[roseus/CMakeLists.txt] add CATKIN_ENABLE_TESTING section for testing

---

roseus/euslisp/roseus-utils.l

pcdファイルをdumpするときのサイズが違っていたのを修正しました。

[roseus-utils.l] fix dump-pointcloud-to-pcd-file file

---

roseus/roseus.cpp

```
[roseus] /home/wkentaro/ros/indigo/src/jsk-ros-pkg/jsk_roseus/roseus/roseus.cpp: In function cell* ROSEUS_SET_PARAM(context*, int, cell**):
[roseus] /home/wkentaro/ros/indigo/src/jsk-ros-pkg/jsk_roseus/roseus/roseus.cpp:1224:12: warning: unused variable nu [-Wunused-variable]
[roseus]    numunion nu;
[roseus]             ^
[roseus] /home/wkentaro/ros/indigo/src/jsk-ros-pkg/jsk_roseus/roseus/roseus.cpp:1227:10: warning: unused variable d [-Wunused-variable]
[roseus]    double d;
[roseus]           ^
[roseus] /home/wkentaro/ros/indigo/src/jsk-ros-pkg/jsk_roseus/roseus/roseus.cpp:1228:7: warning: unused variable i [-Wunused-variable]
[roseus]    int i;
[roseus]        ^
[roseus] /home/wkentaro/ros/indigo/src/jsk-ros-pkg/jsk_roseus/roseus/roseus.cpp: In function cell* …
```

[roseus] Remove definition of unused variables in roseus.cpp

---

roseus_mongo/README.md
roseus_mongo/euslisp/mongo-client.l
roseus_mongo/test/test-mongo-client.l

calling `(mongo::query msg)` without mongodb server stucks on waiting server response forever.
This pull request sets `~timeout` option to avoid this stuck.
- [README.md] refactor markdown. / add description for timeout option
- [euslisp/mongo-client.l] support timeout
- [test/test-mongo-client.l] add test for query with timeout

[roseus_mongo] query mongo server with timeout option

---

roseus_smach/src/pddl2smach.l

double check to avoid error reported at https://github.com/euslisp/EusLisp/issues/210

[roseus_smach/src/pddl2smach.l] use function namespace to call

---

roseus_mongo/euslisp/json/json-decode.l

fix: from comment https://github.com/jsk-ros-pkg/jsk_roseus/commit/4fd758ce55ec64cf21098a14098d4d7d9570148a#commitcomment-20430551

[roseus_mongo][json-decode.l] fix: parse-number / constant return only string

---

roseus_mongo/euslisp/mongo-client.l
roseus_mongo/test/test_mongo_client.test

`ros::get-param` always returns numerial value as `double` instead `*mongo-service-timeout*` assumes parameter as `integer`.

[roseus_mongo] fix: timeout must be integer

---

roseus/CMakeLists.txt
roseus/roseus.cpp
roseus/roseus_c_util.c

```
Warnings   << roseus:make /home/k-okada/catkin_ws/ws_roseus/logs/roseus/build.make.009.log
/home/k-okada/catkin_ws/ws_roseus/src/jsk_roseus/roseus/roseus.cpp: In member function ‘uint32_t EuslispMessage::serializationLength() const’:
/home/k-okada/catkin_ws/ws_roseus/src/jsk_roseus/roseus/roseus.cpp:250:13: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
pointer a,curclass;
^
/home/k-okada/catkin_ws/ws_roseus/src/jsk_roseus/roseus/roseus.cpp: In member function ‘virtual uint8_t* EuslispMessage::serialize(uint8_t*, uint32_t) const’:
/home/k-okada/catkin_ws/ws_roseus/src/jsk_roseus/roseus/roseus.cpp:260:13: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
pointer a,curclass;
^
/home/k-okada/catkin_ws/ws_roseus/src/jsk_roseus/roseus/roseus.cpp: In …
```

remove compiler warning from roseus.cpp

---

roseus_smach/sample/parallel-state-machine-sample.l
roseus_smach/src/state-machine-utils.l
roseus_smach/test/test-parallel-state-machine.l

add `:root-name` key to `exec-state-machine` function.
this is for two state machine running parallel.

[roseus_smach] add root-name key in exec-state-machine

---

roseus/euslisp/roseus-utils.l

```make-camera-from-ros-camera-info-aux``` may return wrong camera position
if projection matrix has base_line (it is for stereo cameras)
definition of CameraInfo // (elt P 3) = fx * base_line[m]
https://github.com/ros/common_msgs/blob/jade-devel/sensor_msgs/msg/CameraInfo.msg#L97-L98
current make-camera-from-ros-camera-info-aux // tx = (elt P 3), fx = (elt P 0)
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/euslisp/roseus-utils.l#L42-L48
implementation of jskeus // tx = base_line[mm], fx = fx
https://github.com/euslisp/jskeus/blob/master/irteus/irtsensor.l#L388-L393
So, it requires unit conversion [mm -> m] and calc baseline from (elt P 3).
After this PR, eus model is changed collectly.
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/make-pr2-model-file.l
~~~ …

[roseus_utils.l] fix make-camera-from-ros-camera-info-aux

---

roseus/CMakeLists.txt

compiled version of roseus displays
```
roseus ;; loading roseus("") on euslisp((9.23 ip-172-31-23-158 Mon Mar 13 06:38:31 PDT 2017  1.1.0))
```
this should be
```
roseus ;; loading roseus("1.6.1") on euslisp((9.23 ip-172-31-23-158 Mon Mar 13 06:38:31 PDT 2017  1.1.0))
```

CMakeLists.txt: use grep package.xml when git --tags did not retun any message (it happens in build farm)

---

roseus/euslisp/actionlib.l

wait-for-reault takes at least 0.1 sec and 0.2 sec at the worst.
https://github.com/start-jsk/rtmros_common/issues/1017
By current code, order of processing is processing-message, spin, wait. So, 'wait' always is on between getting message and processing message.
Then, changing the location of spinning and shortening waiting time can solve this problem.

[roseus/euslisp/actionlib.l] fix :wait-for-result is too slow

---

roseus_mongo/euslisp/json/json-decode.l
roseus_mongo/test/test-json-decode.l

Fix for handling decoding json with escaped string values

roseus_mongo: fix decode escaped string

---

roseus/euslisp/roseus.l
roseus/test/test-geneus.l

add test to check https://github.com/jsk-ros-pkg/jsk_roseus/pull/537 / https://github.com/jsk-ros-pkg/jsk_robot/issues/823 and rewrited  version of #357 
Closes jsk-ros-pkg/jsk_robot#823

package without msg does not have manifest.l, so skip loading that without  ros::ros-error

---

roseus_smach/src/state-machine-utils.l
roseus_smach/test/test-roseus-smach-utils.l

currently, we need to pass `userdata` keys manually.
with this PR, we just set `userdata` in exex-smach, and keys are automatically set.

[roseus_smach] pass userdata keys to state-machine in execution

---

roseus/roseus.cpp

Calling `(ros::rate XX)` in main loop causes gradual memory leak?

roseus.cpp: use boost::shared_ptr for ros::Rate

---

roseus/euslisp/actionlib.l
roseus/test/simple-client-test.l

see #543
actionlib.l:send-goal : send-goal accepts both ActionGoal and Goal, where
Python and C only takes Goal, but original roseus takes ActoinGoal, here we
make ActionGoal when Goal is passed as python/c client
send SimpleGoal, not SimpleActionGoal

Support both AcitonGoal and Goal in :send-goal

---

roseus/euslisp/roseus.l
roseus/roseus.cpp
roseus/test/test-roseus.l

Closes #458
- test/test-roseus.l : add test for ors::duration-sleep
- roseus.cpp/roseus.l : add ros::duration-sleep
examples : 
```
(setq tm0 (ros::time-now))
(send (instance ros::duration :init 1.5) :sleep)
(setq tm1 (ros::time-now))
(assert (eps= (send (ros::time- tm1 tm0) :to-sec) 1.5 0.2))
(setq tm0 (ros::time-now))
(send (instance ros::duration :init 2 500000000) :sleep)
(setq tm1 (ros::time-now))
(assert (eps= (send (ros::time- tm1 tm0) :to-sec) 2.5 0.2))
(setq tm0 (ros::time-now))
(ros::duration-sleep 0.5)
(setq tm1 (ros::time-now))
(assert (eps= (send (ros::time- tm1 tm0) :to-sec) 0.5 0.2))
```

add ros::duration-sleep

---

roseus/euslisp/roseus.l
roseus/roseus.cpp

Closes #554 
package does not have msg/srv does not have manifest.l under `share/roseus/ros/<pkg>` but exists `share/<pkg>`,
previous logic skips this situation and load manifest.l from `/opt/ros/indigo/share/roseus/ros/<pkg>`
Fixed log to check if we have `share/<pkg>` but does not have `share/roseus/ros/<pkg>`, returns `:no-msg-packages`
c.f. https://github.com/jsk-ros-pkg/jsk_robot/issues/823

do not load manifest.l when we have source tree, but does not have manifest.l because of missing msg/srv

---

roseus_smach/CMakeLists.txt
roseus_smach/sample/fibonacci-server.l
roseus_smach/sample/state-machine-ros-sample.l
roseus_smach/sample/state-machine-sample.l
roseus_smach/src/state-machine-actionlib.l
roseus_smach/src/state-machine-utils.l
roseus_smach/src/state-machine.l
roseus_smach/test/smach-action-client-state-in-server.l
roseus_smach/test/test-action-client-state-in-server.l
roseus_smach/test/test-action-server.l
roseus_smach/test/test-samples.l
roseus_smach/test/test_action_client_state_in_server.test
roseus_smach/test/test_action_server.test
roseus_smach/test/test_samples.test

rewrite #558
- Fix: indentations
- Fix: [bug] values set as userdata are completely lost if not given as arguments
- Fix: weird vector value set to :cancel for userdata in state-machine-action-server
- Add: Test code for action-client-state / state-machine-action-server class
- Add: action-client-state sets action result/feedback to userdata for key :result/:feedback

Bugfixes and test codes for roseus_smach

---

roseus/euslisp/roseus.l

if the last argument is shorter than 7,  error occurs .
~~~
Call Stack (max depth: 20):
0: at (subseq (car (last lisp::*eustop-argument*)) 0 7)
1: at (string= "__log:=" (subseq (car (last lisp::*eustop-argument*)) 0 7))
2: at (if (string= "__log:=" (subseq (car (last lisp::*eustop-argument*)) 0 7)) (progn (ros-info "install ros::roseus-sigint-handler") (setq *exit-on-fatal-error* t) (lisp::install-error-handler 'roseus-error) (unix:signal unix::sigint 'roseus-sigint-handler) (unix:signal unix::sighup 'roseus-sigint-handler) (defmacro user::do-until-key (&rest forms) (cons 'while (cons 't (append forms nil)))) (defun y-or-n-p (&rest args) t)))
3: at (when (string= "__log:=" (subseq (car (last lisp::*eustop-argument*)) 0 7)) (ros-info "install ros::roseus-sigint-handler") (setq …

[roseus.l] add length check for argument when searching __log:=

---

roseus/CMakeLists.txt

`catkin_make` fails to compile roseus, see https://travis-ci.org/jsk-ros-pkg/geneus/builds/452694267

use PROJECT_SOURCE_DIR instaed of CMAKE_SOURCE_DIR for `catkin_make`

---

roseus_smach/src/state-machine-utils.l
roseus_smach/src/state-machine.l

The `userdata` on smach is lost and passed to the next state when no `:arg-keys` (for remapping userdata keys) is set.

roseus_smach: pass userdata unless :arg-keys is set

---

roseus/roseus.cpp

set locale to none to print non-ascii string in log message.
```lisp
$ roseus
3.irteusgl$ (ros::roseus "hhh")
4.irteusgl$ (ros::ros-info "ああ")
[ INFO] [1543630431.664127838] [/hhh_1543630392650267207:ros.roseus]: ??????
```
```lisp
$ roseus
1.irteusgl$ (ros::roseus "aaa")
t
2.irteusgl$ (ros::ros-info "あああ")
[ INFO] [1543630616.720022552] [/aaa_1543630597079538450:ros.roseus]: あああ
t
```

roseus: setlocale to none

---

roseus/euslisp/roseus-utils.l

in one-shot-publish function, ros::time's method's name is wrong.
This PR fixed it.

[roseus-util.l] Fixed typo :tosec -> :to-sec

---

roseus_smach/test/test-samples.l

re-enable test removed in #567 
```
;; removed since it is always failling on only installed test https://api.travis-ci.org/v3/job/406576370/log.txt
;; not sure why...
;;   start testing [test-smach-action-client-state]
;;   m;p=pointer?(0x6252338)
;;   ;; Segmentation Fault.
;;   terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
;;   what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```
c.f. https://github.com/jsk-ros-pkg/jsk_roseus/pull/567#issuecomment-406841511

check why test-smach-action-client-state failing on installed test

---

roseus/euslisp/roseus.l

Actually noticed some unmatching parenthesis on `roseus.l`, so am reporting it.

Remove unmatched parenthesis

---

roseus/CMakeLists.txt
roseus/euslisp/roseus-utils.l
roseus/test/test-print-ros-msg.l
roseus/test/test-print-ros-msg.test

Ignoring `_connection-header`, `plist` and any other slots added to the `ros::object` class when printing ros messages with `print-ros-msg`.
Strictly speaking this makes the `(eq (symbol-package sm) rp)` part pointless, which leads to having `rp` as an unused argument. This is not changed to maintain backward compability.
https://github.com/jsk-ros-pkg/jsk_roseus/pull/605

Ignore _connection-header in 'print-ros-msg'

---

roseus/euslisp/roseus.l
roseus/test/test-roseus.l

Allows to load pathnames, which are supported in `eus` but leads to the following error in `roseus`.
```lisp
$ (load #P"/tmp/test.l")
;; sequence expected in (substringp "package://" fname)
```

Allow to load pathnames

---

roseus_tutorials/launch/hsi_color_filter.launch
roseus_tutorials/package.xml
roseus_tutorials/src/display-bounding-box-array.l

Moved from #613 
I added `display-bounding-box-array.l` as an example of visualizing the result of `hsi_color_filter.launch` in roseus_tutorials.

[roseus_tutotrials] Add euslisp example using hsi_color_filter

---

roseus/bin/roseus.in

I've been needing some more debugging aid in euslisp, and decided to run roseus with gdb on, as pointed out in the roseus executable itself.
~~Not much difference, but in this PR am updating the gdb related comment to use the same irteusgl executable as the standard command.~~
EDIT:
Incorporating @k-okada suggestion to add an command line argument `--gdb` to start roseus in the gdb mode.

Add command line option to start roseus with gdb

---

roseus/euslisp/roseus-utils.l

Related to https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/396
Also, removed unmatched parenthesis in roseus-utils.l (similar fix was #607)

Return t after calling service in (call-empty-service service)

---

roseus_smach/README.md

I add `smach_viewer` to run_depend in package.xml.
When I run sample codes in README, smach_viewer is not found.
Although smach_viewer is not used in scripts under src/ and sample/ directories, I think smach_viewer should be in run_depend to run README sample codes easily.

[roseus_smach] add smach_viewer to run_depend

---

roseus/euslisp/roseus.l

there is no method called load-ros-msg/srv
I fix to recommend ros::roseus-add-msgs/srvs

fix warning message for load-ros-manifest

---

roseus/euslisp/roseus-utils.l
roseus/package.xml
roseus/test/test-roseus.l

I added functions to convert `shape_msgs/SolidPrimitive` <-> `euslisp object`
`shape_msgs/SolidPrimitive` is used at collision-object-publisher.l, for example.
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus_moveit/euslisp/collision-object-publisher.l#L80-L85
If this pull request is merged, I will replace the above code with cube->shape-msg() functions.

add functions to convert shape_msgs/SolidPrimitive <-> euslisp object

---

roseus/euslisp/eustf.l

The original comment was incorrect.
`:lookup-transform` returns the transform from **target_frame** to **source_frame**. (not from **source_frame** to **target_frame**)
https://github.com/ros/geometry/issues/108
https://answers.ros.org/question/229463/confusing-tf-transforms/
https://uenota.github.io/dronedoc/appendix/trouble_shooting/subpages/ros/reversed_tf.html
https://github.com/jsk-ros-pkg/jsk_recognition/issues/1269

[eustf.l] fix comment of :lookup-transform

---

roseus_smach/sample/parallel-state-machine-sample.l

When I execute `rosrun roseus_smach parallel-state-machine-sample.l`, I got the following error.
```
Call Stack (max depth: 20):
0: at (require :state-machine "package://roseus_smach/src/state-machine.l")
1: at (require :state-machine "package://roseus_smach/src/state-machine.l")
irteusgl: ERROR th=0  file #P"package/roseus_smach/src/state-machine.l" not found in (require :state-machine "package://roseus_smach/src/state-machine.l")E:
```
This PR fixes this bug.

[roseus_smach] use roseus for parallel-state-machine-sample

---

roseus/euslisp/eustf.l

The original comment ended in the middle of the sentence.

[eustf.l] add comment to :wait-for-transform

---

roseus/euslisp/eustf.l

I fixed typo: `geoometry` -> `geometry`

Fix typo: geoometry -> geometry

---

roseus/package.xml

I found duplicated dependencies in package.xml in roseus.
`<build_depend>visualization_msgs</build_depend>`
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/package.xml#L30
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/package.xml#L39
`<run_depend>visualization_msgs</run_depend>`
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/package.xml#L57
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/package.xml#L64

[roseus] Remove duplicated dependency in package.xml

---

roseus/roseus.cpp

Updated the `ros::advertise-service` function documentation based on the #679 changes and following the `ros::subscribe` style.
```
defun(ctx,"SUBSCRIBE",argv[0],(pointer (*)())ROSEUS_SUBSCRIBE,
"topicname message_type callbackfunc args0 ... argsN &optional (queuesize 1) &key (:groupname groupname)\n\n"
...
```

Update advertise-service function documentation

---

roseus_smach/src/state-machine-utils.l

sorry, I forgot fixing this typo.
`(send sm :spin-once)` -> `(send insp :spin-once)`

[roseus_smach] fix typo in state-machine-utils.l

---

roseus/euslisp/actionlib.l

The `:cancel-callback` method of simple-action-server was setting the `check-func` variable at global scope.
At first I thought it was a slot variable, but that does not seem to be the case.

Fix check-func variable scope in ros::simple-action-server

---

.travis.yml
roseus/test/param-test.l
roseus/test/test-add-two-ints.l

to pass test on noetic, we need to fix test
1) `roseus/test/test-param.l` , from noetic, `roslaunch` set `/roslaunch/uris/host_` params.
```
(setq diff (remove-if #'(lambda (x) (substringp "/roslaunch/uris/host_" x)) diff)) ;; from noetic roslaunch set params https://github.com/ros/ros_comm/blob/07fb5469c71e10e4a05fa3a631897d9adece61c5/tools/roslaunch/src/roslaunch/launch.py#L448-L449
```
2) `roseus/test/test-add-two-ints.l` Call service call sometimes fails, it happens in melodic too, we recommend to use persistent service call for similar examples.
```
(assert (= (+ (send req :a) (send req :b)) (send res :sum))
;; https://github.com/ros/ros_comm/issues/1976
;; service call sometimes fail
(when (not (= (+ (send req :a) (send req :b)) (send res :sum)))
(incf service-call-error) …
```

add noetic test on travis

---

roseus/.gitignore
roseus/defun.h

`defun.h` is auto-generated during the build, but was added in https://github.com/jsk-ros-pkg/jsk_roseus/pull/702
In this PR I am reverting this and adding the `defun.h` to gitignore.

Ignore auto-generated defun.h

---

roseus/roseus.cpp
roseus/test/param-test.l
roseus/test/test-parameter.test

Allows to recursively set values organized in alists at `ros::set-param`.
```yaml
that:
test:
a: 1
b:
- 1
- 2
- 3
```
```lisp
(ros::roseus "test")
(ros::get-param "/that")
;; (("test" ("a" . 1) ("b" 1 2 3)))
(ros::set-param "/this" (ros::get-param "/that"))
(ros::get-param "/this")
;; (("test" ("a" . 1) ("b" 1 2 3)))
```
Needs discussion & testing.
Partially related to https://github.com/jsk-ros-pkg/jsk_roseus/issues/709

Allow to recursively set alists with string keys in ros::set-param

---

roseus_smach/src/state-machine-utils.l

This PR enables us to change /server_name manually.
This change is important for smach_to_mail.py because the node name of all smach containers that use exec-state-machine sets `/server_name`.

[roseus_smach] Add :srv-name key to exec-state-machine to set server_name manually

---

roseus/roseus.cpp

This PR supports float value for `wait-for-service`
```
2.irteusgl$ (bench (ros::wait-for-service "/hoge" 0.1))
[ INFO] [1669893179.246469328]: waitForService: Service [/hoge] has not been advertised, waiting...
;; time -> 0.112254[s]
nil
3.irteusgl$ (bench (ros::wait-for-service "/hoge" 0.5))
[ INFO] [1669893182.724133362]: waitForService: Service [/hoge] has not been advertised, waiting...
;; time -> 0.500441[s]
nil
4.irteusgl$ (bench (ros::wait-for-service "/hoge" 1.7))
[ INFO] [1669893188.485341099]: waitForService: Service [/hoge] has not been advertised, waiting...
;; time -> 1.70549[s]
nil
5.irteusgl$ (bench (ros::wait-for-service "/hoge" 2))
[ INFO] [1669893198.351550769]: waitForService: Service [/hoge] has not been advertised, waiting...
;; time -> 2.00875[s]
nil
```
``` …
```

[roseus] use float for waitForService

---

roseus/euslisp/actionlib-commstate.l

```lisp
(apropos "lost")
;; actionlib_msgs::goalstatus::*lost*  Constant=9
;; actionlib_msgs::lost
;; ros::*lost*
;; unix::siglost  Constant=29
```

Fix actionlib_msgs::lost -> actionlib_msgs::GoalStatus::*lost*

---

roseus/test/test-add-two-ints.l

relax test condition for test-add-two-ints without persistent. we expect service call sometime fails without persistent

test-add-two-ints.l:  relax test condition

---

roseus/euslisp/actionlib.l
roseus/test/test-simple-server-cancel.l
roseus/test/test-simple-server-cancel.test

While working on https://github.com/jsk-ros-pkg/jsk_roseus/pull/672 I found out that when interrupted the euslisp server return the status 6 (preempting), while the same actionlib_tutorials node returns 2 (preempted).
This turned out to be happening from a misuse of the `case` function with multiple match cases in a single sentence, which are evaluated as quoted strings (symbols not values) and therefore are virtually unreachable. As a proof there was also a typo in the actionlib_msgs::GoalStatus::\*pree**p**mpting\* variable.

Fix case function misuse in simple-action-server :set-preempted

---

README.md
roseus/bin/roseus.in

When running `$ roseus --gdb "(load \"package://pr2eus/pr2-interface.l\")" "(pr2-init)"` on the simulator, the program stops at the following breakpoint.
```
Thread 3 "irteusgl" hit Breakpoint 1, 0x00007fffec8a0c20 in XmlRpc::XmlRpcUtil::error(char const*, ...)@plt () from /opt/ros/melodic/lib/libxmlrpcpp.so
#0  0x00007fffec8a0c20 in XmlRpc::XmlRpcUtil::error(char const*, ...)@plt ()
from /opt/ros/melodic/lib/libxmlrpcpp.so
#1  0x00007fffec8a1af2 in XmlRpc::XmlRpcClient::writeRequest() ()
from /opt/ros/melodic/lib/libxmlrpcpp.so
#2  0x00007fffec8a25a6 in XmlRpc::XmlRpcClient::handleEvent(unsigned int) ()
from /opt/ros/melodic/lib/libxmlrpcpp.so
#3  0x00007fffec8a351f in XmlRpc::XmlRpcDispatch::work(double) ()
from /opt/ros/melodic/lib/libxmlrpcpp.so
#4  0x00007fffecfa7e38 in …
```

Avoid setting breakpoints at other namespaces when using --gdb option

---

roseus_smach/src/state-machine-ros.l

when I try to use statemachine with more than 10 submachines, smach_viewer cannot visualize it properly.
in this PR,
- fix the problem with the publisher init sleep problem
- avoid too quick publishication of smach structure

[roseus_smach] Fix problems with statemachine with 10~ submachines

---

roseus/roseus.cpp

`(wait-for-service server-name timeout)` be called with `nil` or `negative` value.
this PR check if the `argv[1]` is `nil` or not and `positive` or not, and ignore if it is `nil` or `negative`.

[roseus] check if argv[1] is nil in `wait-for-service`

---

roseus_smach/sample/sample_smach_exit_state.launch
roseus_smach/sample/state-machine-ros-sample.l
roseus_smach/src/state-machine-ros.l
roseus_smach/src/state-machine-utils.l
roseus_smach/src/state-machine.l

I add `exit-state` and `register-signal-exit-state` to execute exit-state when Ctrl-C pressed.
You can try with this launch + diff
```xml
<launch>
<node pkg="roseus_smach" type="state-machine-ros-sample.l" name="state_machine_ros_sample"
args="&quot;(exec-smach-simple)&quot;" output="screen" />
</launch>
```
```diff
diff --git a/roseus_smach/sample/state-machine-ros-sample.l b/roseus_smach/sample/state-machine-ros-sample.l
index f6b24e3..95da645 100755
--- a/roseus_smach/sample/state-machine-ros-sample.l
+++ b/roseus_smach/sample/state-machine-ros-sample.l
@@ -43,7 +43,7 @@
sm ))
-(defun exec-smach-simple () (setq count 0) (exec-state-machine (smach-simple)))
+(defun exec-smach-simple () (setq count 0) (exec-state-machine (smach-simple) nil :exit-state :bar))
(defun exec-smach-nested () …
```

[roseus_smach] add exit-state in state-machine and execute exit-state when Ctrl-C

---

roseus_smach/CMakeLists.txt

closes
```
2025-02-13T10:17:18.5985936Z -- Installing devel-space wrapper /github/home/ws/src/executive_smach_visualization/smach_viewer/test/test_rosout_error.py to /github/home/ws/devel/.private/smach_viewer/share/smach_viewer/test
2025-02-13T10:17:18.5986753Z -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
2025-02-13T10:17:18.5987263Z -- [roseus.cmake] loading roseus.cmake from smach_viewer
2025-02-13T10:17:18.5987550Z -- [roseus.cmake] roseus 1.7.5
2025-02-13T10:17:18.5987761Z -- [roseus.cmake] jskeus
2025-02-13T10:17:18.5987960Z -- [roseus.cmake] euslisp
2025-02-13T10:17:18.5988166Z -- [roseus.cmake] geneus 3.0.0
2025-02-13T10:17:18.5988384Z -- [roseus.cmake] genmsg 0.5.16
2025-02-13T10:17:18.5988881Z -- [roseus.cmake] message_generation Requires: …
```

remove euslisp from CATKIN_DEPENDS, as euslisp is not catkin package from ROS-O
