jsk-ros-pkg/jsk_roseus

- roseus/test/test-genmsg-oneworkspace.rosbuild.launch
- roseus/test/test-genmsg.rosbuild.launch
- roseus/test/test-genmsg.sh
This is discussed at https://github.com/jsk-ros-pkg/jsk_roseus/pull/236
> Add test for new geneus

- roseus/test/test-genmsg.sh
using messages which is not within message_generation but build depends
this is expected fail
> [test-genmsg.sh] add roseus_dep3

- .travis.yml
- roseus/CMakeLists.txt
- roseus/scripts/generate-all-msg-srv.sh
- roseus/test/test-genmsg.sh
- setup_upstream.sh
- [generate-all-msg-srv.sh] write list of packages ONLY contains msg/srv
- [roseus/CmakeLists.txt] add rosnode to find_package
> fix message generation

- roseus_smach/src/state-machine-utils.l
By parameter state-machine,  state-machine is set nil.
> modify make-state-machine

- .travis.yml
- roseus/cmake/roseus.cmake
- [.travis.yml] add jsk_pr2eus as downstream check
- [.travis.yml] rewrite using global section
> add downstream check (pr2eus)

- roseus_smach/src/state-machine.l
*  active state is  set the last state of previous states' next state.(False)
* set active state lists of next states of previous states.
> [roseus_smach] modify state-machine :execute-impl

- roseus_smach/sample/parallel-state-machine-sample.l
This is splitted out from https://github.com/jsk-ros-pkg/jsk_roseus/pull/293
> [roseus_smach] fix wrong file/module name

- roseus_smach/sample/state-machine-ros-sample.l
- roseus_smach/src/state-machine-utils.l
- roseus_smach/test/test-async-join-state-machine-actionlib.l
- roseus_smach/test/test-samples.l
function `smach-exec` is used in another files.
> [roseus_smach] move smach-exec function from sample to utils

- roseus/euslisp/roseus-utils.l
- [euslisp/roseus-utils.l] support bodyset object
- [euslisp/roseus-utils.l] support random color
- [euslisp/roseus-utils.l] support object with :glvertices
> add more option to eusobj->marker-msg

- roseus/roseus.cpp
- roseus/test/test-roseus.l
inspired by http://docs.ros.org/indigo/api/roscpp/html/master_8h.html
> [roseus.cpp] add get-host, get-nodes, get-port, get-uri, get-topics

- roseus/cmake/roseus.cmake
hot fix for https://github.com/jsk-ros-pkg/jsk_roseus/issues/312
> [roseus] Add NO_GENERATE_EUSDOC environmental variable to disable generation of eusdoc

- roseus/euslisp/roseus-utils.l
- roseus/test/test-roseus.l
@aginika please merge this one before your https://github.com/jsk-ros-pkg/jsk_roseus/pull/327 commit, and confirm this PR fails and fixed by your PR
- [test/test-roseus.l] add test code for marker message <-> eus object conversion function in euslisp/roseus-utils.l
> add test code for marker/eus conversion

- .travis.yml
- roseus/cmake/get_all_depends.py
- roseus/cmake/roseus.cmake
- roseus/test/test-genmsg.catkin.test
- roseus/test/test-genmsg.sh
to fix problem https://github.com/jsk-ros-pkg/jsk_roseus/pull/319 and 
https://github.com/jsk-ros-pkg/geneus/issues/33
[test/test-genmsg.sh] add test to check if messages in roseus is generated
> add test code to check if roseus message genration is working

- roseus_smach/README.md
- roseus_smach/sample/state-machine-ros-sample.l
- roseus_smach/sample/state-machine-sample.l
> Fix smach viewer readme

- roseus_mongo/euslisp/mongo-client-sample.l
forgot to update sample code with change of https://github.com/jsk-ros-pkg/jsk_roseus/pull/343
> [roseus_mongo/euslisp/mongo-client-sample.l] fix: update sample

- roseus/CMakeLists.txt
- roseus/euslisp/roseus.l
- roseus/test/test-compile-message.l
- roseus/test/test-compile-message.test
- [euslisp/roseus.l] fix roseus-add-files to use normal compile-file-if-src-newer
- add test for compiling message
> refacter compile message

- roseus/euslisp/actionlib.l
show warning message when action server is not found.
> add warning message when action server is not found

- roseus_smach/CMakeLists.txt
- roseus_smach/src/state-machine-utils.l
- roseus_smach/test/test-roseus-smach-utils.l
- roseus_smach/test/test_roseus_smach_utils.test
> [roseus_smach] add failure nodes addition feature for state-machine generation utils

- .travis.rosinstall
- roseus_mongo/euslisp/mongo-client-sample.l
- roseus_mongo/euslisp/mongo-client.l
- roseus_mongo/test/test-mongo-client.l
Test should fail
waiting for https://github.com/strands-project/mongodb_store/pull/147
> [roseus_mongo] add limit option for query

- .travis.yml
- roseus/CMakeLists.txt
- roseus/package.xml
- roseus/test/test-actionlib.test
> roseus/test/test-actionlib.test: re-enable test-actionlib.test, which is disabled since groovy

- roseus_smach/src/state-machine.l
https://github.com/jsk-ros-pkg/jsk_roseus/pull/383#issuecomment-153257520
> [roseus_smach/src/state-machine.l] another impl for #383

- roseus_smach/src/state-machine-utils.l
Currently connection to/from nil state is ignored.
This PR fixes this problem.
> [roseus_smach/src/state-machine-utils.l] fix: smach connection from/to nil state

- README.md
> Add document about how to run roseus on gdb

- roseus/cmake/roseus.cmake
```
[naoqieus] -- [roseus.cmake] naoqieus will compile naoqieus                                   
[naoqieus] CMake Warning at /home/jsk/k-okada/catkin_ws/ws_fetch/src/jsk_roseus/roseus/cmake/roseus.cmake:88 (find_package): 
[naoqieus]   By not providing "Findnaoqieus.cmake" in CMAKE_MODULE_PATH this project has      
[naoqieus]   asked CMake to find a package configuration file provided by "naoqieus",         
[naoqieus]   but CMake did not find one.                                                      
[naoqieus]                                                                                    
[naoqieus]   Could not find a package configuration file provided by "naoqieus" with any      
[naoqieus]   of the following names: …
```
> cmake/roseus.cmake: quiet find_pakcage, this may fail for the first time

- setup_upstream.sh
Why?
----
- I prefer setting repo_slug of the repository for wstool
- I think this does not break current setup
> Refactor 'setup_upstream.sh'

- setup_upstream.sh
> Fix typo in 'setup_upstream.sh'

- .travis.yml
> After failure only on travis

- .travis.yml
- roseus/package.xml
#Modified:
- .travis.yml
- roseus/package.xml
Related to https://github.com/jsk-ros-pkg/jsk_roseus/pull/393#issuecomment-155425662
> [roseus] Set xvfb as test_depend and stop installing it before_script

- roseus/CMakeLists.txt
- roseus/cmake/roseus.cmake
euslisp should be installed via Homebrew on OS X
> [roseus] Fix building on OS X

- roseus/cmake/roseus.cmake
just to set SOURCE_PREFIX, this will solve https://github.com/jsk-ros-pkg/jsk_robot/issues/597
> when pkg is target package do not need to find_package

- roseus/CMakeLists.txt
on arm64 system, CMAKE_SYSTEM_PROCESSOR returns aarch64
> fix for aarch64

- .travis.yml
- roseus/CMakeLists.txt
- roseus/test/test-geneus.test
- roseus_mongo/CMakeLists.txt
- add kinetic test - msg generation is only required unil indigo
- mongo is > only released from indigo
- .traavis.yml shdo not set INSTALL_SRC when INSTALL_SRC_SECURE is not set
> add kinetic test

- .travis.yml
- roseus/CMakeLists.txt
travis is failing ... https://travis-ci.org/jsk-ros-pkg/jsk_roseus/jobs/233858193
> skip test/test-genmsg.catkin.test

- .travis.yml
currently all travis job on master branch fails : https://s3.amazonaws.com/archive.travis-ci.org/jobs/243474937/log.txt?X-Amz-Expires=30&X-Amz-Date=20170616T103442Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJRYRXRSVGNKPKO5A/20170616/us-east-1/s3/aws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=971a99f29b70e6d3d8a0b14b1ab8897828868e1277ec981c9cdd685e7c61e38d
> kill X server in .travis.yml

- .travis.yml
- roseus/roseus.cpp
https://github.com/jsk-ros-pkg/jsk_roseus/pull/530#issuecomment-315005357
> [roseus][roseus.cpp] check ros::ok() in ros::spin

- .travis.rosinstall.hydro
- roseus_mongo/CMakeLists.txt
- roseus_mongo/README.md
- roseus_mongo/euslisp/json/json-decode.l
- roseus_mongo/euslisp/json/json-utils.l
- roseus_mongo/euslisp/mongo-client-sample.l
- roseus_mongo/euslisp/mongo-client.l
- roseus_mongo/test/test-json-decode.l
- roseus_mongo/test/test-mongo-client.l
- Added non blocking insertion
- Added test code
- Added docstrings
- Fixed deprecated codes
> roseus_mongo: support non blocking insertion & update docstring

- roseus/CMakeLists.txt
- roseus/msg/TestName.msg
- roseus/test/test-name-pub.l
- roseus/test/test-name-sub.l
- roseus/test/test-name.test
C.f. #508 
This is very interesting, though we could not reproduce.
> [WIP] add test code for [unexpected behavior if message has property `name`] #508

- roseus/CMakeLists.txt
- roseus/eustf.cpp
- roseus/roseus.cpp
- roseus/roseus_c_util.c
- roseus_tutorials/package.xml
see https://github.com/euslisp/jskeus/pull/511 and https://github.com/euslisp/EusLisp/pull/116
- force generate defun.h header file
- use euslisp(9.24)'s new defun api roseus.cpp taht takes doc as argument, remove _defun
- add documentation string to defun functions
- add documentation string to defun functions, (roseus_c_util.c uses NULL because this is not exported functions)
> update function using new defun function

- roseus/euslisp/eustf.l
- roseus/test/test-tf.l
Add code to wait for transform in test-frame-exists by @Affonso-Gui 
Cf #591, add test code first, and then commit fixed code
> add test-frame-exists

- roseus/roseus.cpp
- roseus/test/test-add-two-ints.l
- roseus/test/test-add-two-ints.test
- roseus/test/test-service-callback.l
> roseus: reuse service server/client link on service call if connection is valid

- roseus/test/add-two-ints-client.l
> read request values from argument

- roseus/euslisp/actionlib.l
- roseus/test/simple-client-test.l
Reverts jsk-ros-pkg/jsk_roseus#578
> Revert "roseus: add :last-status-msg method for simple-action-client"

- roseus/test/test-roseus.l
> Add test load-pathname

- .travis.yml
Fix sourcing travis.sh
c.f. https://github.com/jsk-ros-pkg/jsk_travis/pull/385#issuecomment-544325484
> Fix source travis.sh

- roseus_smach/README.md
I think roseus_smach is very convenient to use and it helped me a lot with coding rather complex codes.
However, displaying only samples in README is somewhat unfriendly to new users. So I added some explanation in `README.md`. 
My understanding may be incorrect, so it would be great if someone can review the README and correct it. 
Thank you!!
> [roseus_smach] add code explanation of simple-state-machine in README.md. 

- roseus/test/say.l
- roseus_tutorials/src/aques-talk.l
- roseus_tutorials/src/vision-action-example1.l
- roseus_tutorials/src/vision-action-example2.l
set volume for kinetic
see https://github.com/jsk-ros-pkg/jsk_control/pull/724#issuecomment-513127598 for discussion
> add SoundRequest.volume for kinetic

- .travis.yml
Closes
```
Errors << geneus:cmake /home/travis/ros/ws_jsk_roseus/logs/geneus/build.cmake.000.log
CMake Error at /home/travis/ros/ws_jsk_roseus/src/geneus/CMakeLists.txt:1 (cmake_minimum_required)
CMake 3.0.2 or higher is required.  You are running version 2.8.12.2
```
> indigo does not have CMake 2.8

- roseus/euslisp/actionlib.l
> fix typo in actionlib.l

- roseus_smach/README.md
- roseus_smach/sample/state-machine-sample.l
- roseus_smach/src/state-machine.l
- roseus_smach/test/test-samples.l
- roseus_smach/test/test_samples.test
- add more info(URL/python code) on sample
- fix typo of nestate state machine example path
- add make-sample-parallel-state-machine tests
- add more test, check :active-tates, duration time
> update README.md and add more tests

- roseus_smach/src/state-machine-ros.l
- roseus_smach/src/state-machine-utils.l
add `:groupname` argument in `state-machine-inspector`
> [roseus_smach] add groupname in state-machine-inspector

- roseus_smach/src/pddl2smach.l
I add more `ros-info` in `convert-smach`.
> [roseus_smach] add more ros-info in convert-smach

- roseus_smach/src/state-machine.l
add `:append-goal-state` method in `state-machine`.
current implementation, we need to `:remove-node` and set `:goal-state` for appending `goal-state`.
> [roseus_smach] add :append-goal-state

- .github/workflows/config.yml
- use gazebo from http://packages.osrfoundation.org/gazebo/ubuntu, force download ~/.gazebo/models to pass pr2eus_moveit tests
c.f. https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/479
> fix github action

- roseus/euslisp/roseus-utils.l
- copied from https://github.com/jsk-ros-pkg/jsk_robot/pull/1376/files#diff-c70afdbf438eacc1424a31e609ab4e3d94460ba0d89d03df4004fef168731d56
- add timeout key
- use persist mode for call-*-service, see https://github.com/jsk-ros-pkg/jsk_roseus/pull/593
> add call-trigger-service and call-set-bool-service, copied from

- roseus_smach/src/state-machine.l
this PR add `:flatten` option `roseus_smach`.
`:nodes` methods + `:flatten t` shows all nodes in nested submachines.
`:node` methods + `:flatten t`  search the node from all nodes in nesterd submachines.
```
2.irteusgl$ (send *sm* :nodes)
(#<state #X562f116af2a8 :correct-by-leader> #<state #X562f116af260 :finish> #<state #X562f116a8968 他の客の会計> #<state #X562f116a8938 他の客の机の片付け> #<state #X562f116a88f0 会計> #<state #X562f116a88a8 机の片付け> #<state #X562f116a8878 料理提供> #<state #X562f116a8830 オーダー受け> #<state #X562f116a8800 オーダー待ち> #<state #X562f116a87b8 お冷や提供> #<state #X562f116a6748 席へのご案内> #<state #X562f116a6718 お迎え（ご案内）>)
3.irteusgl$ (send *sm* :node "「いらっしゃいませ」")
nil
```
```
4.irteusgl$ (send *sm* :nodes :flatten t)
(#<state #X562f116af2a8 :correct-by-leader> #<state #X562f116af260 :finish> …
```
> [roseus_smach] add flatten option for submachine search

- roseus_mongo/README.md
I put a brief summary of how to handle json in roseus because I forget every time...
> [roseus_mongo][json] Add handling JSON example to README

- .github/workflows/config.yml
see https://github.com/jsk-ros-pkg/jsk_common/pull/1808
> fix CI: update jsk_travis 0.5.27, override node20 https://github.com/actions/upload-artifact/issues/616#issuecomment-2350667347

- .github/workflows/config.yml
- roseus/CMakeLists.txt
- roseus/bin/roseus.in
- roseus/euslisp/roseus.l
we want to catch
```
2025-01-09T23:21:03.1534333Z [ 62%] Generating ../sample/rimokon-pose.launch, ../sample/milktea-box.launch
2025-01-09T23:21:03.1549833Z cd /<<BUILDDIR>>package/sample && ROS_PACKAGE_PATH=/<<BUILDDIR>>package:/opt/ros/one\/share roseus ./pose_detector_auto_gen_sample.l
2025-01-09T23:21:03.1768586Z /opt/ros/one/bin/roseus: line 29: /<<BUILDDIR>>package/sample/(pushnew "/opt/ros/one\/share/roseus/euslisp/" *load-path* :test #'equal): No such file or directory
2025-01-09T23:21:03.1772988Z make[4]: *** [CMakeFiles/eusmodel_template.dir/build.make:86: ../sample/rimokon-pose\.launch] Error 127
2025-01-09T23:21:03.1774161Z make[4]: Leaving directory '/<<BUILDDIR>>package/.obj-x86_64-linux-gnu'
2025-01-09T23:21:03.1777610Z make[3]: *** [CMakeFiles/Makefile2:6445: …
```
> add ROS-O test
